"use client";

import * as React from "react";

/**
 * The hero/header background: a faint network of nodes and connecting lines,
 * with a handful of pulses travelling the edges like signals firing.
 *
 * Layout is a fixed, hand-generated scatter (see the generator note below) —
 * not computed at runtime — so the static network is identical on server and
 * client and never causes a hydration mismatch. Only the animated pulses are
 * client-only, added after mount so a reduced-motion visitor never receives
 * them at all (checked once, matching the pattern in components/reveal.tsx).
 *
 * A radial mask keeps the network faint behind whatever text sits on top of
 * it and lets it show more toward the edges — visible, not distracting.
 */

// Generated by a seeded throwaway script (13x7 jittered grid, ~12% cells
// dropped, 2-3 nearest-neighbour edges per node, quadratic control points
// offset perpendicular to the chord) and pasted in as static data. [x, y, r].
const NODES: [number, number, number][] = [
  [32, 28, 2.2], [111, 15, 3.4], [175, 22, 2.2], [288, 43, 2.2],
  [418, 36, 2.2], [488, 41, 3.4], [570, 26, 2.2], [660, 42, 2.2],
  [742, 39, 2.2], [820, 22, 2.2], [864, 24, 2.2], [975, 33, 2.2],
  [59, 106, 2.2], [182, 100, 2.2], [288, 75, 2.2], [354, 89, 2.2],
  [402, 82, 2.2], [508, 80, 3.4], [561, 99, 2.2], [710, 75, 2.2],
  [820, 100, 1.6], [866, 101, 2.2], [117, 142, 2.2], [204, 154, 3.4],
  [269, 152, 2.2], [337, 161, 3.4], [444, 138, 2.2], [497, 152, 3.4],
  [590, 159, 3.4], [643, 159, 3.4], [713, 149, 2.2], [816, 163, 2.2],
  [864, 142, 3.4], [974, 162, 2.2], [51, 213, 2.2], [126, 197, 2.2],
  [212, 211, 3.4], [288, 221, 2.2], [362, 224, 2.2], [410, 221, 2.2],
  [512, 204, 3.4], [576, 195, 2.2], [670, 203, 2.2], [731, 225, 2.2],
  [787, 213, 2.2], [889, 213, 2.2], [111, 261, 1.6], [176, 256, 2.2],
  [275, 277, 3.4], [359, 267, 3.4], [428, 283, 2.2], [495, 270, 2.2],
  [592, 258, 2.2], [636, 270, 1.6], [736, 257, 2.2], [817, 278, 2.2],
  [865, 277, 2.2], [940, 282, 2.2], [119, 322, 3.4], [253, 327, 2.2],
  [352, 336, 3.4], [415, 315, 3.4], [493, 345, 2.2], [597, 328, 2.2],
  [647, 331, 2.2], [741, 315, 3.4], [827, 343, 1.6], [982, 338, 2.2],
  [57, 391, 3.4], [192, 403, 1.6], [280, 403, 2.2], [324, 385, 2.2],
  [407, 405, 2.2], [491, 395, 2.2], [657, 396, 1.6], [710, 380, 2.2],
  [828, 402, 2.2], [960, 376, 2.2],
];

// Quadratic edges: [x1, y1, cx, cy, x2, y2].
const EDGES: [number, number, number, number, number, number][] = [
  [32, 28, 70, 11, 111, 15], [32, 28, 36, 70, 59, 106],
  [111, 15, 142, 31, 175, 22], [111, 15, 83, 60, 59, 106],
  [175, 22, 230, 43, 288, 43], [175, 22, 177, 61, 182, 100],
  [288, 43, 275, 59, 288, 75], [288, 43, 319, 69, 354, 89],
  [418, 36, 453, 41, 488, 41], [418, 36, 395, 73, 354, 89],
  [418, 36, 403, 56, 402, 82], [488, 41, 529, 36, 570, 26],
  [488, 41, 496, 61, 508, 80], [570, 26, 614, 38, 660, 42],
  [570, 26, 546, 60, 508, 80], [570, 26, 573, 63, 561, 99],
  [660, 42, 701, 30, 742, 39], [660, 42, 679, 68, 710, 75],
  [742, 39, 780, 25, 820, 22], [742, 39, 726, 57, 710, 75],
  [820, 22, 842, 32, 864, 24], [820, 22, 820, 61, 820, 100],
  [864, 24, 919, 38, 975, 33], [864, 24, 862, 63, 866, 101],
  [975, 33, 922, 69, 866, 101], [59, 106, 82, 134, 117, 142],
  [182, 100, 150, 122, 117, 142], [182, 100, 201, 124, 204, 154],
  [288, 75, 321, 80, 354, 89], [354, 89, 379, 93, 402, 82],
  [354, 89, 335, 123, 337, 161], [402, 82, 423, 110, 444, 138],
  [508, 80, 535, 87, 561, 99], [508, 80, 478, 112, 444, 138],
  [508, 80, 508, 117, 497, 152], [561, 99, 565, 134, 590, 159],
  [710, 75, 714, 112, 713, 149], [820, 100, 843, 110, 866, 101],
  [820, 100, 831, 132, 816, 163], [820, 100, 837, 126, 864, 142],
  [866, 101, 871, 122, 864, 142], [866, 101, 920, 131, 974, 162],
  [117, 142, 92, 185, 51, 213], [117, 142, 111, 171, 126, 197],
  [204, 154, 237, 157, 269, 152], [204, 154, 205, 183, 212, 211],
  [269, 152, 303, 153, 337, 161], [269, 152, 275, 188, 288, 221],
  [337, 161, 339, 197, 362, 224], [444, 138, 469, 149, 497, 152],
  [497, 152, 503, 179, 512, 204], [590, 159, 616, 149, 643, 159],
  [590, 159, 589, 179, 576, 195], [643, 159, 677, 145, 713, 149],
  [643, 159, 648, 186, 670, 203], [713, 149, 685, 171, 670, 203],
  [816, 163, 839, 150, 864, 142], [816, 163, 796, 185, 787, 213],
  [864, 142, 921, 142, 974, 162], [864, 142, 865, 182, 889, 213],
  [974, 162, 934, 192, 889, 213], [51, 213, 89, 209, 126, 197],
  [51, 213, 86, 231, 111, 261], [126, 197, 106, 226, 111, 261],
  [126, 197, 147, 230, 176, 256], [212, 211, 251, 207, 288, 221],
  [212, 211, 186, 227, 176, 256], [288, 221, 270, 246, 275, 277],
  [362, 224, 386, 227, 410, 221], [362, 224, 368, 246, 359, 267],
  [410, 221, 381, 240, 359, 267], [410, 221, 418, 252, 428, 283],
  [512, 204, 546, 211, 576, 195], [512, 204, 491, 234, 495, 270],
  [576, 195, 588, 226, 592, 258], [670, 203, 697, 224, 731, 225],
  [731, 225, 761, 231, 787, 213], [731, 225, 732, 241, 736, 257],
  [787, 213, 809, 242, 817, 278], [889, 213, 868, 242, 865, 277],
  [889, 213, 908, 252, 940, 282], [111, 261, 144, 268, 176, 256],
  [111, 261, 120, 291, 119, 322], [111, 261, 76, 323, 57, 391],
  [176, 256, 147, 288, 119, 322], [275, 277, 318, 280, 359, 267],
  [275, 277, 270, 305, 253, 327], [359, 267, 368, 303, 352, 336],
  [359, 267, 379, 300, 415, 315], [428, 283, 464, 287, 495, 270],
  [428, 283, 430, 302, 415, 315], [495, 270, 491, 307, 493, 345],
  [592, 258, 612, 270, 636, 270], [636, 270, 611, 295, 597, 328],
  [636, 270, 630, 303, 647, 331], [736, 257, 747, 285, 741, 315],
  [817, 278, 841, 286, 865, 277], [817, 278, 777, 292, 741, 315],
  [817, 278, 823, 310, 827, 343], [865, 277, 902, 281, 940, 282],
  [940, 282, 960, 311, 982, 338], [940, 282, 957, 328, 960, 376],
  [119, 322, 96, 363, 57, 391], [253, 327, 219, 362, 192, 403],
  [253, 327, 266, 365, 280, 403], [352, 336, 386, 332, 415, 315],
  [352, 336, 334, 358, 324, 385], [352, 336, 386, 365, 407, 405],
  [493, 345, 489, 370, 491, 395], [597, 328, 621, 340, 647, 331],
  [597, 328, 632, 357, 657, 396], [647, 331, 656, 363, 657, 396],
  [741, 315, 729, 349, 710, 380], [741, 315, 782, 361, 828, 402],
  [827, 343, 835, 372, 828, 402], [982, 338, 977, 360, 960, 376],
  [57, 391, 124, 400, 192, 403], [192, 403, 236, 409, 280, 403],
  [280, 403, 300, 389, 324, 385], [324, 385, 369, 382, 407, 405],
  [407, 405, 451, 413, 491, 395], [657, 396, 681, 380, 710, 380],
  [710, 380, 769, 390, 828, 402], [828, 402, 896, 401, 960, 376],
];

/** Edge indices that carry a pulse, each with its own duration and delay. */
const PULSES: { edge: number; dur: number; delay: number }[] = [
  { edge: 4, dur: 5.6, delay: 1.2 },
  { edge: 12, dur: 6.2, delay: 1 },
  { edge: 14, dur: 5.4, delay: 2.2 },
  { edge: 18, dur: 4.7, delay: 0.1 },
  { edge: 23, dur: 5.6, delay: 2.7 },
  { edge: 26, dur: 4.1, delay: 1.9 },
  { edge: 33, dur: 6, delay: 3.8 },
  { edge: 35, dur: 5.6, delay: 0.4 },
  { edge: 37, dur: 5.3, delay: 3.9 },
  { edge: 41, dur: 4.3, delay: 0.4 },
  { edge: 43, dur: 6.2, delay: 1.4 },
  { edge: 75, dur: 4.7, delay: 0.5 },
  { edge: 96, dur: 5.5, delay: 2 },
  { edge: 111, dur: 5.6, delay: 2.9 },
  { edge: 112, dur: 5.1, delay: 1.5 },
  { edge: 116, dur: 5.2, delay: 4.5 },
];

export function NeuralField({
  className,
  tone = "light",
}: {
  className?: string;
  /** "light" for white/near-white sections, "dark" for the pink CTA bands. */
  tone?: "light" | "dark";
}) {
  const [motionAllowed, setMotionAllowed] = React.useState(false);
  // Most pages render this twice (a header + the closing CTA band). Edge ids
  // must stay unique per instance, or every <mpath> on the page resolves to
  // whichever <path id="neuron-edge-0"> happens to come first in the DOM.
  const uid = React.useId();

  React.useEffect(() => {
    const query = window.matchMedia("(prefers-reduced-motion: reduce)");
    setMotionAllowed(!query.matches);
  }, []);

  const lineColor = tone === "dark" ? "#ffffff" : "var(--color-accent)";

  return (
    <div
      aria-hidden
      className={className}
      style={{
        maskImage:
          "radial-gradient(ellipse 65% 60% at 50% 42%, transparent 0%, transparent 30%, black 90%)",
        WebkitMaskImage:
          "radial-gradient(ellipse 65% 60% at 50% 42%, transparent 0%, transparent 30%, black 90%)",
      }}
    >
      <svg
        viewBox="0 0 1000 420"
        preserveAspectRatio="xMidYMid slice"
        className="h-full w-full"
      >
        <defs>
          {/* Soft halo behind each travelling pulse. Namespaced per instance
              for the same reason as the edge ids below. */}
          <filter
            id={`neuron-glow-${uid}`}
            x="-150%"
            y="-150%"
            width="400%"
            height="400%"
          >
            <feGaussianBlur stdDeviation="3" />
          </filter>
        </defs>

        {/* Opacity stays at the original 0.16 despite the network being ~3x
            denser. Dropping it to compensate for the extra strokes was a
            mistake: it turned a legible constellation into an indistinct
            haze. The radial mask below is what keeps it off the copy. */}
        <g stroke={lineColor} strokeOpacity="0.16" fill="none">
          {EDGES.map(([x1, y1, cx, cy, x2, y2], i) => (
            <path
              key={i}
              id={`neuron-edge-${uid}-${i}`}
              d={`M ${x1} ${y1} Q ${cx} ${cy} ${x2} ${y2}`}
              strokeWidth="1.2"
            />
          ))}
        </g>

        <g fill={lineColor} fillOpacity={tone === "dark" ? "0.3" : "0.28"}>
          {NODES.map(([x, y, r], i) => (
            <circle key={i} cx={x} cy={y} r={r} />
          ))}
        </g>

        {motionAllowed
          ? PULSES.map(({ edge, dur, delay }, i) => (
              // Halo + core travel together: animateMotion on the group moves
              // both, and the shared opacity fade keeps the glow in step.
              <g key={i}>
                <circle
                  r="6"
                  fill="var(--color-accent-bright)"
                  opacity="0.35"
                  filter={`url(#neuron-glow-${uid})`}
                />
                <circle r="2.4" fill="var(--color-accent-bright)" />
                <animateMotion
                  dur={`${dur}s`}
                  begin={`${delay}s`}
                  repeatCount="indefinite"
                >
                  <mpath href={`#neuron-edge-${uid}-${edge}`} />
                </animateMotion>
                <animate
                  attributeName="opacity"
                  values="0;0.9;0"
                  keyTimes="0;0.5;1"
                  dur={`${dur}s`}
                  begin={`${delay}s`}
                  repeatCount="indefinite"
                />
              </g>
            ))
          : null}
      </svg>
    </div>
  );
}
